### ISSUE TITLE
Suggestion: remove pure crystals

### ISSUE THREAD

**Issue by ironsnake345** [xFeew/create-sky-factory#1]
Being able to duplicate quartz, apatite, niter, and cinnabar obviously makes sense, but why have the result of growth be a pure crystal? Sure, it looks cool, but it can't be used for all the same recipes; only authentic, non-purified nether quartz can be used to make cobblestone into diorite, or diorite into granite, for example. I can't honestly think of a gameplay reason to have the pure crystals. If there's something I'm missing, that's all well and good, but if it's just there to differentiate it from before the seed-based duplication, why keep that differentiation in there if it's so much more work to add in all the recipes from before it was duplicated?

**Comment by xFeew** [comment]
Pure crystals form beacause they are made using the spout and carefully precisely spouting liquid on them, that makes them grow in a controllable manner without any external inputs like in a natural environment. I will make all recipes that require the crystal input to be interchangeable with the pure version of them.
