### ISSUE TITLE
Crash on attempt to load pack

### ISSUE THREAD

**Issue by LucasErG** [xFeew/create-sky-factory#3]
When attempting to load version 0.1.2d the pack crashes during the loading process. The error message that is put up on the crash screen is as follows: "Create: Crystal Clear (create_crystal_clear) has failed to load correctly. java.lang.reflect.InvocationTargetException: null"
[crash-2024-11-04_17.34.30-fml.txt](https://github.com/user-attachments/files/17624611/crash-2024-11-04_17.34.30-fml.txt)
[latest.log](https://github.com/user-attachments/files/17624612/latest.log)

**Comment by xFeew** [comment]
Thats a mod issue, happens all the time in multiple modpacks. Restarting the game eventually runs correctly. I can't fix that in any way unfortunately.

**Comment by xFeew** [comment]
Closing it as not planned since can't resovlve it.

**Comment by Grumbledore667** [comment]
Sorry to necro this. I had this issue before. Did the update then the Create deco mod broke. Now i updated alll the mods and forge to version 43.3.5 and everything works again :D awesome :D
